### PR TITLE
Get all components of game side

### PR DESCRIPTION
**Pull request by ShiningElektra**
Issue #5 
Issue #6

### CODE REVIEW

**Review by m-wiemers — APPROVED** [review]
GJ! 🚀

**Review by phlgr — CHANGES_REQUESTED** [review]
GJ 🚀 
There is a minor visual bug with the garbage bins where the last sprite shows a bit of the sprite before.
Also the images in the Menu don't seem to load, Maybe because you removed the `/Logo.png` in the PR?

**Review by phlgr — COMMENTED** [review]
The paths still seem broken as the Menu is referencing `/Logo.png` and `/Schrift.png`.
You can check out what I mean here: https://recycool-app-shiningele-k3uvaz.herokuapp.com/storybook/index.html?path=/story/common-menu--open
I would probably change the paths in the Menu Component as the naming proposed here is better than the old one 😄

**Review by phlgr — APPROVED** [review]
Gj 🚀 ♻️

**Pull request merged**
